# Generated by Django 4.0.3 on 2022-04-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageStores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productimages',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table=None,
        ),
    ]
