# Generated by Django 4.0.3 on 2022-04-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mycustomuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
