# Generated by Django 4.0.3 on 2022-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mycustomuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
