# Generated by Django 4.0.3 on 2022-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_mycustomuser_groups_mycustomuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
